version: 2.1

jobs:
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli  # SonarQube Scanner image
    steps:
      - checkout  # Pull latest code from repo
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=djangoecom \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONARQUBE_HOST_URL \
              -Dsonar.login=$SONARQUBE_TOKEN
              
  sonarqubewithshallow:
    docker:
      - image: sonarsource/sonar-scanner-cli  # SonarQube Scanner image
    steps:
      - run:
          name: shallow checkout # Pull latest code from repo
          command: git clone --depth 1 --branch circleci-project-setup https://github.com/AMITSINGHHACKS/odoo.git
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=djangoecomclone \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONARQUBE_HOST_URL \
              -Dsonar.login=$SONARQUBE_TOKEN
  
  build:
    docker:
      - image: cimg/base:stable  # Base CircleCI image
    steps:
      - checkout  # Pull latest code from repo
      - setup_remote_docker  # Enable Docker-in-Docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/djangoecom:latest .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/djangoecom:latest
       
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - sonarqube
      - sonarqubewithshallow
      - build:
          type: approval
          requires:
            - sonarqube
